// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bylclbsmohnzohudvfft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bGNsYnNtb2huem9odWR2ZmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Nzc5MjMsImV4cCI6MjA2NDU1MzkyM30.kC-GY1jJB78T-vlB2VTOSssl-IbQAD0VuN5Nfe8FBXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);